### PR TITLE
Merge intro.js history back with legal license

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by niftylettuce** [comment]
Not doing this until Github gets back to me about his poor practices with licensing

**Comment by graingert** [comment]
@niftylettuce GitHub have no legal standing here. All you're doing is choosing the "Open Source" license option and creating a fork. However to comply with the open source license, you MUST acknowledge the original intro.js.

**Comment by niftylettuce** [comment]
@graingert GitHub DOES have a position here.  It's unethical to change the license of a project multiple times and deliberately confuse people.  I put the original MIT back in, but what is your position here anyways?  Do you work for Usabiliclicalicalicalica?  I am sure GitHub will demand they go MIT license and most importantly ONLY MIT license, it would be super wrong of them to not do such a thing.  Otherwise they will have a leading GitHub contributor go ham and make sure to take traffic away from them with what is planned.

**Comment by graingert** [comment]
@niftylettuce I am merely a co-conspirator in these sorts of shenanigans. (See https://wow.js.org and http://mynameismatthieu.com/WOW/)

It's not unethical to change the license, MIT is designed to allow the license to be changed, (Eg to commercial or GPL). Just as you are free to use intro.js in commercial applications, and are free to use intro.js in a new application with a MIT license that consists only of intro.js, so is afshinm free to use intro.js in a new application with a GPL license that consists only of intro.js.

In fact afshinm does not even need to comply with the MIT as he owns the copywright.

However, what he can't do is "put the genie" back in the bottle, and force licensees to use old copies of intro.js under the new license.

GitHub cannot demand that usabilica "go MIT license"

**Comment by graingert** [comment]
The best way to deal with these sorts of licensing changes, is to fork the product at the commit just before the GPL license, then make a better, more popular product.

**Comment by niftylettuce** [comment]
Okay then I will put out my own version perhaps, named something even better for SEO, and then make money off it to compete with him.  And then ten other people will do the same thing, or even better, someone will come out with a better version of this spaghetti garbage.

**Comment by graingert** [comment]
You can't just break copyright law, demand licensing changes from GitHub, or go ham. :)

**Comment by graingert** [comment]
> Okay then I will put out my own version perhaps, named something even better for SEO
You'll have to change the name from introjs-mit

**Comment by niftylettuce** [comment]
1758 lines of garbage anyways, lmao

https://github.com/usablica/intro.js/blob/master/intro.js#L1758

**Comment by graingert** [comment]
I'm happy to maintain a legal MIT fork if you provide me the names on npm/bower.

**Comment by graingert** [comment]
see also https://github.com/graingert/mit-intro

**Comment by graingert** [comment]
@niftylettuce the AGPL version has landed, please consider pulling in the latest history from before the license change.

**Comment by niftylettuce** [comment]
I really don't care about that package anymore, I found something better.

On Wed, Jul 6, 2016 at 6:41 AM, Thomas Grainger <notifications@github.com>
wrote:

> @niftylettuce <https://github.com/niftylettuce> the AGPL version has
> landed, please consider pulling in the latest history from before the
> license change.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/niftylettuce/introjsmit/pull/2#issuecomment-230738516>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAf7hUoY4aW7dN-9H_aIjQnKBnLjRupPks5qS4ZZgaJpZM4JEhHG>
> .
>



-- 
@niftylettuce

**Comment by graingert** [comment]
@niftylettuce can you assign me the names on npm and bower please.

**Comment by graingert** [comment]
@niftylettuce can you assign me the names on npm and bower please.

I'd like to maintain this project.

**Pull request closed without merging**
